[job]
system = ["nnodes.job", "Local"]
name = "embarrassingly-parallel"
nnodes = 1
account = "GEO111"
walltime = 10.0
gap = 2.0
debug = true
# Add description for number of cpus per node manually..
cpus_per_node = 4


[root]
task = ["hello", "main"]
workflowname = 'Embarrassingly Parallel'

